### ISSUE TITLE
[스프린트 #1] 앱서버 팀 작업 - 프로젝트의 기본 작업 다지기

### ISSUE THREAD

**Issue by ohRyungyi** [21WelfareForEveryone/WelfareForEveryone#4]
- MVC 구조 설계
- 소켓 통신 및 Restful.api 적용 방안 조사
- Dialogflow 연동 및 키워드 추출시 mysql DB 내 정보 검색 방안 조사
- 크라우드 서버에서 mysql DB 접근 방안 조사

**Comment by Oxymoron957** [comment]
**작업내용**

1. GCP Server용 VM Instance를 생성하였습니다. 
2. MVC 모델에 따라서 Model, View, Controller와 Util 폴더를 만들었습니다.
3. Util 폴더 안에 db.js파일을 통해 mysql 서버와 연결하였습니다.
4. app.js 파일을 통해 mysql의 연동을 테스트하였습니다. 
5. 안드로이드 App과의 연동은 HTTP 라이브러리인 Volly를 통해 진행하는 것이 좋을 것같습니다.
